var copyrights = {
    "KJ21": "Scripture quotations taken from the 21st Century King James Version®, copyright © 1994. Used by permission of Deuel Enterprises, Inc., Gary, SD 57237. All rights reserved.",
    "ASV": "American Standard Version - Public Domain",
    "AMP": "Scripture quotations taken from the Amplified® Bible (AMP), Copyright © 2015 by The Lockman Foundation. Used by permission. <www.Lockman.org>",
    "AMPC": "Scripture quotations taken from the Amplified® Bible (AMPC), Copyright © 1954, 1958, 1962, 1964, 1965, 1987 by The Lockman Foundation. Used by permission. <www.Lockman.org>",
    "BRG": "Blue Red and Gold Letter Edition™, Copyright © 2012 BRG Bible Ministries. Used by Permission. All rights reserved.",
    "CSB": "The Christian Standard Bible. Copyright © 2017 by Holman Bible Publishers. Used by permission. Christian Standard Bible®, and CSB® are federally registered trademarks of Holman Bible Publishers, all rights reserved.",
    "CEB": "Common English Bible - See <https://www.biblegateway.com/versions/Common-English-Bible-CEB/#copy>",
    "CJB": "Complete Jewish Bible - Copyright © 1998 by David H. Stern.  All rights reserved. No portion of this book may be reproduced, stored in a retrieval system, or transmitted in any form or by any means without prior written permission of the publisher.",
    "CEV": "Contemporary English Version®, Copyright © 1995 American Bible Society. All rights reserved.",
    "DARBY": "Darby's Translation - Public Domain",
    "DLNT": "Disciples' Literal New Testament: Serving Modern Disciples by More Fully Reflecting the Writing Style of the Ancient Disciples. Copyright © 2011 Michael J. Magill. All Rights Reserved. Published by Reyma Publishing.",
    "DRA": "Douay-Rheims - Public Domain",
    "ERV": "Easy-to-Read Version - Copyright © 2006 by Bible League International",
    "ESV": "The ESV® Bible (The Holy Bible, English Standard Version®). ESV® Permanent Text Edition® (2016). Copyright © 2001 by Crossway, a publishing ministry of Good News Publishers. The ESV® text has been reproduced in cooperation with and by permission of Good News Publishers. Unauthorized reproduction of this publication is prohibited. All rights reserved.",
    "ESVUK": "The \"ESV\"; and \"English Standard Version\" are trademarks of Good News Publishers. Use of either trademark requires the permission of Good News Publishers.",
    "EXB": "Scripture taken from The Expanded Bible. Copyright ©2011 by Thomas Nelson. Used by permission. All rights reserved.",
    "GNV": "Geneva Bible, 1599 Edition. Published by Tolle Lege Press. All rights reserved. No part of this publication may be reproduced or transmitted in any form or by any means, electronic or mechanical, without written permission from the publisher, except in the case of brief quotations in articles, reviews, and broadcasts.",
    "GW": "Scripture is taken from GOD’S WORD®, © 1995 God’s Word to the Nations. Used by permission of Baker Publishing Group.",
    "GNT": "Good News Translation® (Today’s English Version, Second Edition), Copyright © 1992 American Bible Society. All rights reserved.",
    "HCSB": "Scripture quotations marked HCSB are taken from the Holman Christian Standard Bible®, Copyright © 1999, 2000, 2002, 2003, 2009 by Holman Bible Publishers. Used by permission. Holman Christian Standard Bible®, Holman CSB®, and HCSB® are federally registered trademarks of Holman Bible Publishers.",
    "ICB": "International Children’s Bible®, Copyright © 2015 by Tommy Nelson, a division of Thomas Nelson, Inc.",
    "ISV": "The Holy Bible: International Standard Version. Release 2.0, Build 2015.02.09. Copyright © 1995-2014 by ISV Foundation. ALL RIGHTS RESERVED INTERNATIONALLY. Used by permission of Davidson Press, LLC.",
    "PHILLIPS": "J.B. Phillips New Testament - The New Testament in Modern English by J.B Phillips copyright © 1960, 1972 J. B. Phillips. Administered by The Archbishops’ Council of the Church of England. Used by Permission.",
    "JUB": "The Jubilee Bible, Copyright © 2000, 2001, 2010 LIFE SENTENCE Publishing",
    "KJV": "King James Version - Public Domain",
    "AKJV": "The Authorized (King James) Version of the Bible (‘the KJV’), the rights in which are vested in the Crown in the United Kingdom, is reproduced here by permission of the Crown’s patentee, Cambridge University Press.",
    "LEB": "Scripture quotations marked (LEB) are from the Lexham English Bible. Copyright 2012 Logos Bible Software. Lexham is a registered trademark of Logos Bible Software.",
    "TLB": "The Living Bible copyright © 1971 by Tyndale House Foundation. Used by permission of Tyndale House Publishers Inc., Carol Stream, Illinois 60188. All rights reserved. The Living Bible, TLB, and the The Living Bible logo are registered trademarks of Tyndale House Publishers.",
    "MSG": "Scripture taken from The Message. Copyright © 1993, 1994, 1995, 1996, 2000, 2001, 2002. Used by permission of NavPress Publishing Group.",
    "MEV": "Scripture taken from the Modern English Version. Copyright © 2014 by Military Bible Association. Used by permission. All rights reserved.",
    "MOUNCE": "THE MOUNCE REVERSE-INTERLINEAR NEW TESTAMENT Copyright © 2011 by Robert H Mounce and William D Mounce. Used by permission. All rights reserved worldwide.",
    "NOG": "Scripture is taken from GOD’S WORD®, © 1995 God’s Word to the Nations. Used by permission of Baker Publishing Group.",
    "NABRE": "New American Bible, revised edition © 2010, 1991, 1986, 1970 Confraternity of Christian Doctrine, Inc., Washington, DC. All Rights Reserved.",
    "NASB": "Scripture taken from the NEW AMERICAN STANDARD BIBLE®, Copyright © 1960, 1962, 1963, 1968, 1971, 1972, 1973, 1975, 1977, 1995 by The Lockman Foundation. Used by permission.",
    "NCV": "Scripture taken from the New Century Version®. Copyright © 2005 by Thomas Nelson. Used by permission. All rights reserved.",
    "NET": "NET Bible® copyright ©1996-2006 by Biblical Studies Press, L.L.C. <http://netbible.com> All rights reserved.",
    "NIRV": "Scripture taken from the Holy Bible, NEW INTERNATIONAL READER'S VERSION®.Copyright © 1996, 1998 Biblica. All rights reserved throughout the world. Used by permission of Biblica.",
    "NIV": "THE HOLY BIBLE, NEW INTERNATIONAL VERSION®, NIV® Copyright © 1973, 1978, 1984, 2011 by Biblica, Inc.® Used by permission. All rights reserved worldwide.",
    "NIVUK": "Holy Bible, New International Version® Anglicized, NIV® Copyright © 1979, 1984, 2011 by Biblica, Inc.® Used by permission. All rights reserved worldwide.",
    "NKJV": "Scripture taken from the New King James Version®. Copyright © 1982 by Thomas Nelson. Used by permission. All rights reserved.",
    "NLV": "New Life Version - © Christian Literature International",
    "NLT": "Scripture quotations are taken from the Holy Bible, New Living Translation, copyright © 1996, 2004, 2007 by Tyndale House Foundation. Used by permission of Tyndale House Publishers, Inc., Carol Stream, Illinois 60188. All rights reserved.",
    "NRSV": "Scripture quotations are from the New Revised Standard Version Bible, copyright © 1989 the Division of Christian Education of the National Council of the Churches of Christ in the United States of America. Used by permission. All rights reserved.",
    "NRSVA": "Scripture quotations are from the New Revised Standard Version Bible: Anglicised Edition, copyright © 1989, 1995 the Division of Christian Education of the National Council of the Churches of Christ in the United States of America. Used by permission. All rights reserved.",
    "NRSVACE": "Scripture quotations are from the New Revised Standard Version Bible: Anglicised Catholic Edition, copyright © 1989, 1993, 1995 the Division of Christian Education of the National Council of the Churches of Christ in the United States of America. Used by permission. All rights reserved.",
    "NRSVCE": "Scripture quotations are from the New Revised Standard Version Bible: Catholic Edition, copyright © 1989, 1993 the Division of Christian Education of the National Council of the Churches of Christ in the United States of America. Used by permission. All rights reserved.",
    "NTE": "Scripture quotations from The New Testament for Everyone are copyright © Nicholas Thomas Wright 2011.",
    "OJB": "The Orthodox Jewish Bible fourth edition, OJB. Copyright 2002, 2003, 2008, 2010, 2011 by Artists for Israel International. All rights reserved.",
    "RSV": "Scripture quotations are from the Revised Standard Version of the Bible, copyright © 1946, 1952, and 1971 the Division of Christian Education of the National Council of the Churches of Christ in the United States of America. Used by permission. All rights reserved.",
    "RSVCE": "Scripture quotations are from The Revised Standard Version of the Bible: Catholic Edition, copyright © 1965, 1966 the Division of Christian Education of the National Council of the Churches of Christ in the United States of America. Used by permission. All rights reserved.",
    "TLV": "Tree of Life (TLV) Translation of the Bible. Copyright © 2015 by The Messianic Jewish Family Bible Society.",
    "VOICE": "The Voice Bible Copyright © 2012 Thomas Nelson, Inc. The Voice™ translation © 2012 Ecclesia Bible Society All rights reserved.",
    "WEB": "The World English Bible is in the Public Domain. That means that it is not copyrighted. However, \"World English Bible\" is a Trademark.",
    "WE": "Taken from THE JESUS BOOK - The Bible in Worldwide English. Copyright SOON Educational Publications, Derby DE65 6BN, UK. Used by permission.",
    "WYC": "Wycliffe Bible Copyright © 2001 by Terence P. Noble. For Extensive Use, please email terry@smartt.com for further information.",
    "YLT": "Young's Literal Translation - Public Domain",
};

copyrights.contains = function(version) {
    if (copyrights[version]) {
        return true;
    }

    return false;
};

module.exports = copyrights;
